### ISSUE TITLE
Could not read from file: /[Project Path]/crypto

### ISSUE THREAD

**Issue by chbert** [pixelmund/svelte-kit-cookie-session#14]
Hi @pixelmund, thanks for doing this project!

I'm trying to get it to run on my project and I get the following error:

18:45:23 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/.pnpm/svelte-kit-cookie-session@1.3.0/node_modules/svelte-kit-cookie-session/dist/utils/crypto/make-crypter.js:9:75: error: Could not read from file: /[Project Path]/crypto

Any idea what could cause this? Thanks in advance!

**Comment by pixelmund** [comment]
I've run into the same issue, since switching to new encryption which uses nodejs builtin `crypto`. For now you can safely ignore it, the project should still run without issues, if not try reloading the page a few times, it's annoying but the project should run fine. This is a weird `vite` issue [#728](https://github.com/vitejs/vite/issues/728), [#792](https://github.com/vitejs/vite/issues/792) which seems like is not happy about node builtins in external modules. I think there is nothing to solve on this packages end. I'm using version `1.3.0` in production right now.  If you like you can open an issue on the vite repo or on the svelte kit one.

**Comment by chbert** [comment]
@pixelmund thanks for the fast response! Ok, good to know and will do 👍
