### ISSUE TITLE
Subdomain Support 

### ISSUE THREAD

**Issue by impactvelocity** [pixelmund/svelte-kit-cookie-session#23]
I am trying to make the session cookie work with subdomains. Right now it's setting the cookie with 'subdomain.localhost', and I would like to set it to the root domain so I can support sessions over subdomains.

How can I do this? :)

Love this package so far!

**Comment by pixelmund** [comment]
Hey i think your problem is solvable. Check out this [cookie options](https://github.com/pixelmund/svelte-kit-cookie-session/blob/d88836e60126f89676d7e31312b3fe53dac08ece/src/utils/cookie.ts#L11). 
```js
 export const handle = handleSession({ cookie: { domain: "root.com" } })
```
You might be able to set the domain to your root domain. But i'm not 100% sure. Maybe you'll have to play around with the samesite option too.

**Comment by impactvelocity** [comment]
Oh great!! I will give that a try!
